branches:
  only:
    - master

dist: trusty
language: python
python:
  - "3.8.8"

install:
  - pip install -r requirements.txt
script:
  - black . --check --diff 
  - pytest

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
    docker login cameritegeneric.azurecr.io -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker build -t cameritegeneric.azurecr.io/lpr-webserver-api -f ./Dockerfile .;
    docker push cameritegeneric.azurecr.io/lpr-webserver-api;
    fi
